### ISSUE TITLE
Zmiana silnika templatów na SLIM

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#11]
Jak księżna tupię nogą i mówie, że nie zrobię nic na tej stronie bez SLIM'a :)

**Comment by kamilkowalski** [comment]
@ipepe najchętniej tak bym zrobił, jednak data ostatniej aktualizacji pluginu Slima dla Jekylla nie napawa mnie optymizmem: https://github.com/slim-template/jekyll-slim

Z drugiej strony są to biblioteki tak proste, że pewnie nie wymagają po prostu żadnych aktualizacji. Sprawdzę lokalnie jak to działa i dam znać.

**Comment by ipepe** [comment]
Ja mogę coś pomóc bo jestem jak najbardziej za. Kwestia jedynie, że przesiadka na SLIM może nie być aż taka prosta jak wpisanie całego kodu do https://html2slim.herokuapp.com/ więc możliwe ewentualne refaktory zrobić najpierw?

**Comment by kamilkowalski** [comment]
@ipepe zgadzam się, ogarnijmy najpierw assety i treść, zróbmy porządek, potem można przenieść do Slima czy Jade żeby łatwiej było utrzymywać i dodawać treści.

**Comment by kamilkowalski** [comment]
Zamykam issue, zrobię reopen jak dojdziemy do momentu w którym można się tym zająć.
