### ISSUE TITLE
Nie piszmy w JS, tylko w CoffeeScript

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#12]
To apropos przesiadki na slim, to też nie zaboli przerzutka na CoffeeScript...

**Comment by kamilkowalski** [comment]
@ipepe tu akurat się nie zgodzę, lepszą alternatywą jest po prostu ES6, który ostatecznie będzie standardem. Poza tym nie sądzę, żebyśmy potrzebowali jakieś mnóstwo JS na tak prostej stronie.

**Comment by ipepe** [comment]
Ja będę stanowczo nalegał.

ES6 nie jest rozwiązaniem niczego, jeszcze długo nie będzie wspierany i nie chroni przed niczym.

Javascript:

``` javascript
[] == "" // => true
```

**Comment by ipepe** [comment]
ES6 w sferze urządzeń mobilnych:
![image](http://i.imgur.com/nFvpC6H.png)
EDIT: JS to taka moja mała specjalizacja więc będę mocno tupał nogą żeby się przerzucić na Coffee. Nie zamierzam używać JSLintera i poprawiać po wszystkich kiepskiego kodu.

**Comment by kamilkowalski** [comment]
@ipepe chodziło mi o [transpiler ES6 do ES5](http://babeljs.io/). CoffeeScript to też kolejny transpiler, w dodatku ze składnią kompletnie nieprzypominającą JavaScript. Pracowałem ostatnie 3 lata przy projektach używających CoffeeScript i teraz każdy nowy plik piszemy po prostu w ES6 (via Babel), bo ma on już niemal wszystko czego brakowało w JS wcześniej a co CoffeeScript zapewniał, minus narzut związany z nauką całkiem nowego języka. Dodatkowo wcięcia w CoffeeScript nawet po tych 3 latach pisania dalej irytują mnie i współpracowników, kiedy lecą błędy kompilacji bo gdzieś się wstawiło ciało lambdy bez wcięcia, ale kto wie gdzie przy ilości callbacków jaka jest w JS i jakości komunikatów o błędach w CS ¯_(ツ)_/¯

To wszystko plus mój wcześniejszy argument, że nie powinno być na tej stronie nawet tyle JavaScriptu, żeby usprawiedliwiało to użycie transpilerów JS, powinny być wystarczające. :)

**Comment by ipepe** [comment]
Ja dla 20 linii użyłbym coffeescriptu :)

**Comment by kamilkowalski** [comment]
Póki co JS mamy bardzo prosty, ponowimy dyskusję jeżeli zauważymy, że wprowadzenie CoffeeScript/ES6 zmniejszy ilość pisania.
