### ISSUE TITLE
Czy strona ma być za Cloudflarem?

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#13]
Jak w tytule

**Comment by kamilkowalski** [comment]
@ipepe co by nam to dało w stosunku do tego co GitHub Pages już nam daje?

**Comment by ipepe** [comment]
Muszę zbadać co daje GitHub pages, bo temat Cloudflare mam całkiem obadany

**Comment by kamilkowalski** [comment]
Jakiś follow-up? Z mojej strony nie wydaje mi się, żebyśmy potrzebowali CloudFlare - GitHub Pages jest wystarczająco odporne na ataki i dostępne, cache też działa poprawnie, strona jest statyczna więc nie ma co się obawiać ataków SQL injection czy czegokolwiek. Poza tym nie będą jej odwiedzać tysiące ludzi dziennie, a jak będą to wtedy możemy się zająć tą kwestią.

**Comment by ipepe** [comment]
:+1: masz rację
