### ISSUE TITLE
Zorganizować zadania. Priorytety, labelki, odpowiedzialni.

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#14]
Proszę aby zadania miały swoje priorytety, żeby odpowiednio je oznaczyć labelkami (bug, feature, refactor). Żeby były przypisane do odpowiednich osób. Priorytety to powinny być odpowiednie labelki. Milestone już raczej nie są nam aż tak potrzebne.

**Comment by kamilkowalski** [comment]
@ipepe Przypisałem labele i osoby gdzie się dało, zgadzam się co do milestone'ów. Nie ma co przesadzać z zarządzaniem projektem. Jeżeli wystarczy taka dokumentacja issues'ów jaka jest to zamknę ten wątek.

**Comment by ipepe** [comment]
Jest świetna <3
