### ISSUE TITLE
Dodanie linku w readme do otworzenia strony

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#15]
Fajnie jak w readme można kliknąć bezpośrednio w link do witryny PJATK-SUM.github.io

**Comment by ipepe** [comment]
Ogólnie spoko, dużo łatwiej teraz odpalić tą stronę. Ale skoro się czepiam to się przyczepię że prawie pół zdania nie wygląda za dobrze jako link. IMO, bym zrobił tak:

```
Strona internetowa specjalizacji Sieci Urządzeń Mobilnych ([link](http://pjatk-sum.github.io/))
```

**Comment by kamilkowalski** [comment]
A to akurat anti-pattern: https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/
