### ISSUE TITLE
Zmiana bazowego template

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#26]
Przy pracy z #3 straciłem chęć do życia jak zobaczyłem to co jest pod spodem strony. Znalazłem dobry landing page na jekylla: 
https://github.com/swcool/landing-page-theme

Proponuję przenieść to co mamy na ten landing page i będziemy dużo zdrowsi... Zwłaszcza jak się porówna wynik yellowlab.tools:
nowy: http://yellowlab.tools/result/eck5sqzu88
stary: http://yellowlab.tools/result/ebqkgocqwb

**Comment by kamilkowalski** [comment]
A czy ten wynik bierze pod uwagę wszystkie assety, których używamy? W czym są największe różnice - nie dałoby się ich poprawić stopniowo zamiast wyrzucać wszystko i zaczynać od nowa ([co nie jest polecaną praktyką](http://www.joelonsoftware.com/articles/fog0000000069.html))?

**Comment by ipepe** [comment]
Tylko że tak na prawdę jeszcze dobrze nie zaczęła działać ta strona. A ma ogromny dług technologiczny! Javascript'y są kompletnie nie do ogarnięcia ( ja się nie podejmuje ). Główny plik CSS ma 1500 lini! Błagam przecież to jest jedna strona. Przez poziom skomplikowania nie będziemy w stanie naprawić złych nagłówków w górnej części strony żeby się dobrze wyświetlały. IMO do śmieci z tym.

**Comment by kamilkowalski** [comment]
Ok, zaproponuj rewrite i zobaczymy.

**Comment by kamilkowalski** [comment]
Zamykam issue bo jest otwarty PR #30
