### ISSUE TITLE
Przycisk przewijania

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#4]
Po zjechaniu na sam dol witryny i nacisnieciu przycisku przewiniecia do góry leci jakis blad w konsoli js

```
TypeError: m.easing[this.easing] is not a function
```

**Comment by kamilkowalski** [comment]
Brakowało jQuery UI, wprowadziłem zmiany po sugestii @korzento - mógłbyś sprawdzić czy wszystko śmiga?

**Comment by ipepe** [comment]
wyglada ok
