### ISSUE TITLE
Zmiana czcionki(?)

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#6]
Coś jest dziwnego z fontem bo u mnie wygląda jakby ktoś w paincie dorobił ogonki w znakach diakrytycznych. Wygląda to strasznie i podejrzewam że nie jest ClearType

**Comment by kamilkowalski** [comment]
Tak, pewnie brakuje Latin Extended w krojach czcionki na Google Fonts. Już dodaję.

**Comment by ipepe** [comment]
Jak byś mógł, to nie zamykaj zadania, jeżeli zgłaszający Ci nie potwierdził że jest już szczęśliwy :)
