### ISSUE TITLE
Błąd: Górny pasek z nawigacją

### ISSUE THREAD

**Issue by ipepe** [PJATK-SUM/PJATK-SUM.github.io#7]
Gdy się naciśnie przycisk "O nas" a potem pojedzie z powrotem na górę strony to pasek nie znika i przez to zasłania, np: logo pjwstk

**Comment by kamilkowalski** [comment]
@ipepe już znika, przypuszczam że błąd był powiązany z #4, możesz sprawdzić?

**Comment by ipepe** [comment]
jest ok
